start-at-login = true
enable-normalization-flatten-containers = false

after-startup-command = ['exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar']
exec-on-workspace-change = ['/bin/bash', '-c', '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE']

[gaps]
outer.top = 40

[mode.main.binding]
cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

alt-s = 'layout v_tiles'
alt-w = 'layout h_tiles'
alt-e = 'layout tiling'
cmd-shift-space = 'layout floating tiling'

alt-h = 'split horizontal'
alt-v = 'split vertical'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 0'


cmd-ctrl-1 = 'move-node-to-workspace 1'
cmd-ctrl-2 = 'move-node-to-workspace 2'
cmd-ctrl-3 = 'move-node-to-workspace 3'
cmd-ctrl-4 = 'move-node-to-workspace 4'
cmd-ctrl-5 = 'move-node-to-workspace 5'
cmd-ctrl-6 = 'move-node-to-workspace 6'
cmd-ctrl-7 = 'move-node-to-workspace 7'
cmd-ctrl-8 = 'move-node-to-workspace 8'
cmd-ctrl-9 = 'move-node-to-workspace 9'
cmd-ctrl-0 = 'move-node-to-workspace 0'

alt-shift-c = 'reload-config'


cmd-ctrl-r = 'mode resize'
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode esc'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "layout floating"
